FROM node:16 AS builder
WORKDIR /client
COPY /client/package.json /client/package.json
COPY /client/package-lock.json /client/package-lock.json
COPY /client/index.html /client/index.html
COPY /client/src /client/src
COPY /client/public /client/public
COPY /client/vite.config.js /client/vite.config.js
RUN npm install
RUN npm run build
EXPOSE 5173:5173
CMD ["npm", "run", "dev"]