FROM node:14
WORKDIR /server
COPY /server/package.json /server/package.json
COPY /server/package-lock.json /server/package-lock.json
COPY /server/src /server/src
RUN npm install
EXPOSE 3000:3000
CMD ["npm", "start"]
